### ISSUE TITLE
Clonging the starter space doesn't work

### ISSUE THREAD

**Issue by Barokai** [kickstartDS/storyblok-starter#13]
hi, when trying to follow the first step
Clone our Starter space by visiting https://app.storyblok.com/#!/build/242426. an error occurs on storyblok side - is this known?
![image](https://github.com/kickstartDS/storyblok-starter/assets/2293949/5b172e49-21cf-4186-9f57-ac30b9ffd8be)

**Comment by julrich** [comment]
Hey @Barokai, we should really clean up that README. Have you had a look at the Netlify Deploy button? That should work, and pretty much only clones and installs the project before, too.

Alternatively you should be able to do it all manually, too. If you don't want to wait for a cleaned up README, feel free to join us on Discord and I'll try to guide you through it!
https://discord.gg/mwKzD5gejY

**Comment by julrich** [comment]
Hey @Barokai, we should really clean up that README. Have you had a look at the Netlify Deploy button? That should work, and pretty much only clones and installs the project before, too.

Alternatively you should be able to do it all manually, too. If you don't want to wait for a cleaned up README, feel free to join us on Discord and I'll try to guide you through it!
https://discord.gg/mwKzD5gejYq

**Comment by Barokai** [comment]
Thanks for the quick reply, no i didn't try the netlify deploy, but will do for sure soon :)
Will probably also join discord

**Comment by julrich** [comment]
Cool, always happy to help along! We'll probably clean up the starters this week, too. It's on our radar for sure!
The involved commands can be seen in the `netlify.toml` for the moment:
https://github.com/kickstartDS/storyblok-starter/blob/main/netlify.toml

It's basically an initial install (`npm i`), followed by an initial `npm run init`. For the `init` to work, you have to define some environment variables in your `env.local`. Which means you'll also need an empty / new Storyblok space before starting! After `npm run init` is ran successfully, you should be able to start locally by running `npm run dev` and `npm run ssl-proxy` (needed for the Visual Preview locally) in parallel!
