### ISSUE TITLE
Error while npm run build

### ISSUE THREAD

**Issue by Jeykom** [kickstartDS/storyblok-starter#23]
Hi,

when i run npm run build (or npm run extract-tokens), i got following error:

<img width="1184" alt="image" src="https://github.com/user-attachments/assets/af847d8b-443c-43bd-95a3-37c8e1781040">

**Comment by julrich** [comment]
Hey @Jeykom, do you also get an error for running `npm run build-tokens`?

I'll have a look at it either way, did quite some restructuring to the README and some parts of the project... maybe I broke something!

**Comment by Jeykom** [comment]
npm run build-tokens seems fine for me

<img width="1075" alt="image" src="https://github.com/user-attachments/assets/90ae7bb6-5fbb-4246-83f8-20074892bd8f">

**Comment by julrich** [comment]
I'll try a reproduction, maybe I really broke something. Will get back to you in a bit!

**Comment by julrich** [comment]
Okay, well... that's on me :smile: 

Should be fixed now in this repo, have a look at this change: https://github.com/kickstartDS/storyblok-starter/commit/348a95a84eb52db11305ee60eb8ebef0e7608a69
You'll want to make that change in your clone / fork, too!

For a bit of background, when running `npm run extract-tokens` (which is also called when running `npm run build`) the existing Design Token from the Design System behind this starter are extracted first, and in a second pass some (that are relevant to the starter) get read and processed from that extraction.
We use this process to minimize the amount of token needed in production, to keep bundle size small.

Those are the scripts doing that extraction / calculation, which is also (the latter one) where you'd add new values you might need when customizing content / components:
- https://github.com/kickstartDS/storyblok-starter/blob/main/scripts/extractComponentToken.js
- https://github.com/kickstartDS/storyblok-starter/blob/main/scripts/calculateCssProperties.js

For the starter, those token are mainly used to calculate optimal image sizes, e.g. according to the Design Token for section widths. This also ensures that when you later changes those values to match your design / brand, those values will get updated, too... resulting in images still being optimally rendered.

Some of that can be seen here:
- https://github.com/kickstartDS/storyblok-starter/blob/main/components/ImageSizeProviders.tsx
- https://github.com/kickstartDS/storyblok-starter/blob/main/components/ComponentProviders.tsx#L68-L71

**Comment by julrich** [comment]
Let me know if this fixes it for you. I did, as mentioned, add quite a host of features / updates to this starter. If you stumble upon anything else, feel free to open issues as you did here!

Also in the process of finishing up the `README.md`. That should be a lot more full-fledged by start of next week, too :blush:

**Comment by Jeykom** [comment]
now i got following 🙈 I stay in this thread because its still related to npm run build:

<img width="934" alt="image" src="https://github.com/user-attachments/assets/6d981a4b-2d67-4c3d-8965-43956cbfcf56">

**Comment by julrich** [comment]
You're right... also fits this issue. Let me give the whole setup procedure a spin again, just to check if there are other errors, too. Shouldn't make you stumble through those :wink:

**Comment by julrich** [comment]
The Design System backing this starter was actually missing some type exports, which are needed here. Fixed it over in that repository: https://github.com/kickstartDS/ds-agency/commit/e2387800167543d45a8c9344e414349df8f09d75

If you update the `@kickstartds/ds-agency` dependency in your `package.json`, and do a quick `npm install`, followed by a `npm run dereference-schemas` and `npm run generate-props`, you should be ready to go now. Also tested the rest quickly, and it seemed to work now :relaxed: 
https://github.com/kickstartDS/storyblok-starter/blob/main/package.json#L46

Sorry for being the guinea pig here :see_no_evil:

**Comment by Jeykom** [comment]
Yeah nice, it seems to work now :D
Big thx for the mega fast reactions

**Comment by julrich** [comment]
No worries, and feel free to add issues / ask questions if something doesn't seem to work, or is unclear!
Feedback like yours is super helpful to us, to smooth out all the edges!
