### ISSUE TITLE
CMS Test: Teaser Card (Free)

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/storyblok-starter#7]
- All Variants
  - [x] `target` should be Storyblok Content Type `Link` not `text`: https://github.com/kickstartDS/storyblok-starter/issues/1
  - [x] `Image` should be Storyblok Content Type `Multi-Asset` (with default Filetype `Image` pre-selected (?)) not text:

Storyblok Schema Types: https://www.storyblok.com/docs/schema-configuration

**Comment by julrich** [comment]
As with https://github.com/kickstartDS/storyblok-starter/issues/8, the remaining issue about the headline of a teaser card not actually rendering its Markdown, this was just an oversight. Fixed now!
