### ISSUE TITLE
CMS Test: Testimonials (Free)

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/storyblok-starter#8]
- [x] Testimonial quote (Text) is a Markdown but the component's text does not support markdown formatting 

![image](https://github.com/kickstartDS/storyblok-starter/assets/85347223/6c7447dd-8f13-40a4-a4bb-8407fd3f6d13)

  Preview works now fine

**Comment by julrich** [comment]
This was an oversight in the Design System component itself, it was missing the markdown compiler for its `quote` property. Added now!
